spring.application.name=backend

spring.datasource.url=jdbc:mysql://database-1.cb2004uo8fsu.eu-north-1.rds.amazonaws.com:3306/backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=qunimade520

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

app.jwt.secret=abcdefghijklmnopqrstuvwxyz0123456789
app.jwt.expiry-hours=12

darwin.access-token=${DARWIN_ACCESS_TOKEN:}

horsepay.api-url=http://homepages.cs.ncl.ac.uk/daniel.nesbitt/CSC8019/HorsePay/HorsePay.php
horsepay.store-id=Team04
